apiVersion: extensions/v1beta1
#kind: ReplicationController
kind: Deployment
metadata:
  name: cci-app
spec:
  replicas: 2
  template:
    metadata:
      name: cci-app
      labels:
        app: cci-app
    spec:
      containers:
      - name: cci
        image: whewawal/concourse-demo
        #command: ["/bin/sh"]
        ports:
        - containerPort: 5000

