apiVersion: v1
kind: ReplicationController
metadata:
  name: concourse-ci-app
spec:
  replicas: 2
  template:
    metadata:
      name: cconcourse-ci-app
      labels:
        app: cconcourse-ci-app
    spec:
      containers:
      - name: cci
        image: whewawal/concourse-ci-prod
        #command: ["/bin/sh"]
        ports:
        - containerPort: 5000

