---
resources:
- name: github-code
  type: git
  source:
    uri: https://github.com/wasanthag/concourse_ci_pipelines.git
    branch: master
    username: {{git_http_user}}
    password: {{git_http_token}}
    #private_key: {{private_key}}

jobs:
- name: unit-test
  public: true
  serial: true
  plan:
  - get: github-code
    trigger: true
  - task: run-unit-test
    config:
      platform: linux
      image_resource: 
        type: docker-image
        source:
          email: {{docker-hub-email}}
          username: {{docker-hub-username}}
          password: {{docker-hub-password}}
          repository: {{docker-hub-base-image}}
      inputs:
        - name: github-code
      run:
        path: github-code/run-unit-test.sh
